// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyfwqkoqequuvgstvvji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5Zndxa29xZXF1dXZnc3R2dmppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2NzE5NTksImV4cCI6MjA0OTI0Nzk1OX0.r6EpgujSuj28U5P4u08BDRPCkrdgsNjLUiG4ltUQufk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);